

#----------- Events Calendar -------------------------------------------------
events:
    path:     /
    defaults: { _controller: "FamilyBundle:Events:index" }
    methods:  GET
    options:
        expose: true

show_all_events:
    path: /events
    defaults: { _controller: "FamilyBundle:Events:showAllEvents" }

events_new:
    path:     /{start}/new
    defaults: { _controller: "FamilyBundle:Events:new"}
    methods:  [GET, POST]

events_edit:
    path:     /{id}/edit
    defaults: { _controller: "FamilyBundle:Events:edit" }
    methods:  [GET, POST]

events_delete:
    path:     /{id}/delete
    defaults: { _controller: "Family:Events:delete" }
methods: [GET, DELETE]
