event_new:
    path:     /{start}/new
    defaults: { _controller: "FamilyBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "FamilyBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "FamilyBundle:Event:delete" }
    methods:  DELETE


#Route pour afficher nos events dans le calendrier
#On l'expose grace à FOSJSRouting afin que notre configuration de FullCalendar puisse l'utiliser
eventsShowOnCalendar:
    path:     /events
    defaults: { _controller: "FamilyBundle:Event:showEventOnCalendar" }
    methods:  GET
    options:
        expose: true