FamilyBundle\Entity\Evenement:
    type: entity
    table: null
    repositoryClass: FamilyBundle\Repository\EvenementRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        start:
            type: datetime
            nullable: true
        end:
            type: datetime
            nullable: true

    lifecycleCallbacks: {  }
